SELECT * FROM employees;
SELECT product_name, product_code FROM products;
SELECT * FROM suppliers;
SELECT * FROM employees WHERE city != 'Redmond';
SELECT product_code, product_name, category FROM products WHERE category != 'beverages';
SELECT * FROM products WHERE standard_cost > 12.0000;
SELECT ship_city, ship_address, shipping_fee FROM orders WHERE shipping_fee BETWEEN 20.0000 AND 78.1223;
SELECT * FROM products WHERE  minimum_reorder_quantity IS NOT NULL;
SELECT * FROM products WHERE minimum_reorder_quantity IS NOT NULL AND standard_cost < 10.0000;
SELECT first_name, last_name, city FROM employees WHERE city LIKE '%nd' and city != 'Redmond';
SELECT * FROM customers WHERE job_title NOT LIKE '%manager%';
SELECT * FROM customers WHERE ( first_name LIKE 'J%' OR last_name LIKE '%o%' ) AND job_title LIKE '%manager%';
SELECT * FROM products WHERE supplier_ids  IN ('4', '6', '7');
SELECT first_name, last_name, city FROM employees WHERE city = 'Redmond' ORDER BY first_name DESC;
SELECT * FROM products ORDER BY standard_cost ASC, list_price DESC;
SELECT DISTINCT job_title FROM customers;
SELECT DISTINCT category FROM products ORDER BY category DESC;
SELECT first_name as imie_pracownika, last_name AS nazwisko_pracownika, city AS miasto FROM employees WHERE city = 'Seattle';
SELECT ship_city AS miasto, ship_address AS adres_dostawy, shipping_fee AS oplata_przewoz FROM orders WHERE shipping_fee BETWEEN 19.1256 AND 78.1999;
SELECT count(*) FROM orders;
SELECT count(*) FROM orders WHERE payment_type = 'Credit Card';
SELECT count(*) FROM orders WHERE payment_type IS NULL;
SELECT MIN(shipping_fee) FROM orders WHERE shipping_fee > 201.0000;
SELECT SUM(shipping_fee) FROM orders;
SELECT AVG(shipping_fee) FROM orders WHERE shipping_fee BETWEEN 10 AND 15;
SELECT MAX(shipping_fee) FROM orders;
SELECT * FROM orders;
SELECT MIN(standard_cost) FROM products WHERE supplier_ids = 1;
SELECT AVG(shipping_fee) FROM orders WHERE shipping_fee > 0;
SELECT * FROM purchase_order_details WHERE product_id = 43;
SELECT SUM(quantity) FROM purchase_order_details WHERE product_id = 43;
SELECT MIN(standard_cost), category FROM products GROUP BY category;
SELECT COUNT(job_title) AS Liczba_pracownikow, job_title AS stanowisko FROM customers group by job_title;
SELECT * FROM products join suppliers ON products.id = suppliers.id;
SELECT company, product_name FROM products JOIN suppliers ON products.id = suppliers.id;
SELECT last_name, first_name, address, city, country_region, payment_type FROM customers JOIN orders ON customers.id = orders.id WHERE payment_type IS NULL;
SELECT * FROM orders LEFT JOIN suppliers ON orders.id = suppliers.id;
SELECT first_name, shipped_date, order_date FROM customers LEFT JOIN orders ON customers.id = orders.id;
SELECT invoice_date AS data_faktury, payment_date AS data_platnosci FROM invoices LEFT JOIN purchase_orders ON invoices.id = purchase_orders.id;
SELECT last_name, job_title, order_date FROM orders RIGHT JOIN employees ON orders.id = employees.id;
